### PR TITLE
Improvements to hardware docs?

### PR DESCRIPTION
**Pull request by taylortrimble**
Hi everyone,

I'm trying to familiarize myself with the project and I am having trouble with finding documentation re: the actual chips we're using. [Hardware Documentation](https://github.com/teslaworksumn/HeadMaster/wiki/Hardware-Documentation) seems to have some info re: physical hardware and pinouts, but nothing re: the micro being used, the operating frequency, etc.

Would it be possible to clarify what PIC we're using, at what frequency it's running, and any known idiosyncrasies with the hardware layout on the table?

Thanks a bunch.

### CODE REVIEW

**Comment by taylortrimble** [comment]
We'll improve the README too.

**Comment by taylortrimble** [comment]
Okay, commit is added. Sorry @mplewis GitHub says you did it since I tacked the PR onto your issue. :stuck_out_tongue_winking_eye: Check out the wording and I'll merge away if you like it.

**Comment by mplewis** [comment]
Looks good to me!

**Pull request merged**
