### PR TITLE
Open source license

### PR DESCRIPTION
**Pull request by taylortrimble**
Once merged, these licensing changes place the project in the open source realm. We can make the project public after that.

Good work everyone!

### CODE REVIEW

**Comment by taylortrimble** [comment]
This pull request closes #20.

**Comment by CrasherCourse** [comment]
Looks like all the files have the proper licenses.

However, you may need to put some newlines into LICENSE.
For me, each paragraph is put on a single line.

**Comment by taylortrimble** [comment]
Good catch. What do you guys think now?

**Comment by kevana** [comment]
Looks good to me.

**Pull request merged**
