### PR TITLE
Range mapping

### PR DESCRIPTION
**Pull request by taylortrimble**
From teslaworksumn/headslave [wiki](https://github.com/teslaworksumn/headslave/blob/master/README.md), the slave chips expect an input value in the range of 30-160 and DMX outputs 0-255. Need to figure out if mapping in the Master controller can be done without a significant performance impact. Ex. (value >> 1) + 30

### CODE REVIEW

**Comment by taylortrimble** [comment]
Okay, and tuned in you are! I've added the code. Tested it in a separate branch, works for our needs.
The vector stuff _only_ works on `unsigned char` types, and is destructive. Same for `mapDmxToServo`.

This is for performance - Hurray! :confetti_ball:

**Comment by kevana** [comment]
Is this ready to be merged in?

**Comment by taylortrimble** [comment]
If you guys don't see anything you don't like, I don't think I'll be adding anything to this really.

**Comment by kevana** [comment]
I like what I see. Manually merging might take a bit but I think sooner is better than later.

**Pull request merged**
