### PR TITLE
Add call to mapDmxToServo in main

### PR DESCRIPTION
**Pull request by kevana**
Addresses #26

### CODE REVIEW

**Comment by taylortrimble** [comment]
Just for the record, if we do decide to use interrupt driven DMX in the future this isn't interrupt safe and we'll need a copy for mucking with. It would be a mistake to include it now however, because we don't need it and it would reduce performance.

**Comment by kevana** [comment]
I must've missed something, I didn't see anything already in master for it.

**Comment by taylortrimble** [comment]
I was talking about using `ReadStartChannel` or whatever we called it in combination with `NUMBER_OF_SLAVES` AND `BYTES_PER_SLAVE` to calculate a pointer offset and smaller buffer size.

**Comment by kevana** [comment]
Ah, yes. Could just use dmxbytesreceived - dmxstartchannel for the array
offset

**Comment by taylortrimble** [comment]
> Ah, yes. Could just use dmxbytesreceived - dmxstartchannel for the array
> offset

I think this is for the wrong issue, I'll put it over there!

**Pull request merged**
