### PR TITLE
Style

### PR DESCRIPTION
**Pull request by taylortrimble**
Update the style! I went through it, and it compiles, but it could use another comb-over I'm sure.

### CODE REVIEW

**Comment by taylortrimble** [comment]
By the way, because I renamed files, the diff is a little ugly. I recommend visiting the `style` branch in the code browser primarily instead— but also tackling the diff wouldn't hurt.

**Comment by taylortrimble** [comment]
@aterlumen, could you remove the `TODO`s in `I2C.h` and the in-code documentation? And could the in-code documentation be moved to the wiki?

**Comment by mplewis** [comment]
I'll take a look.

**Comment by mplewis** [comment]
Code cleaned, [wiki updated](https://github.com/teslaworksumn/HeadMaster/wiki/I2C). Run it by the style guide, if you please?

**Comment by taylortrimble** [comment]
Just a couple of things I found, but I think I'm happy. What does @aterlumen think of me changing all his function and file names?

**Comment by taylortrimble** [comment]
Committing in 3... 2...
That's hours by the way. Let me know what you think!

**Comment by kevana** [comment]
2 hours late, looks good to me.

**Comment by taylortrimble** [comment]
:stuck_out_tongue_winking_eye:

**Pull request merged**
