### PR TITLE
Pull Add inline asm to receive dmx into master branch

### PR DESCRIPTION
**Pull request by kevana**

### CODE REVIEW

**Comment by kevana** [comment]
@tylrtrmbl I think I need to get rid of my commit to README, any simple way to do that?

**Comment by taylortrimble** [comment]
You don't have to throw away your changes. Just try to merge the `master` branch into `Add-inline-ASM-to-receive-DMX`. You can find instructions for merging online.

Otherwise, if you want to throw away the `README.md` commits, you can use the GUI to go back to the commit and hit the "Revert" button. **Don't hit rollback.**

**Comment by taylortrimble** [comment]
@aterlumen sorry for the complexity here, but...
You'll need to pull down _both_ the `master` _and_ the `Add-inline-ASM-to-receive-DMX` branches and _then_ perform a literal merge. I think you had an outdated copy of the README.md file in your master branch.

You can merge updates from the `master` branch when your topic branch is out of date by:
1. Visiting each branch in the Mac GUI (bottom left) and clicking synch branch inside each branch (top right).
2. Going to the fancy graphical branch tab (left side)
3. Going into Merge View (top right, below sync)
4. Merging the `master` branch into the `Add-inline-ASM-to-receive-DMX` branch
5. A commit is automatically made, and you can go sync this up again.

This is how you can avoid having to throw away work (even if it's only a little bit like this time). You would have ended up with a `CONFLICT` file in the GUI after the Merge, and then you can manually resolve it by opening the file.

It has this format, and you just pick the text you want to keep.

```
<<<<<<< HEAD

* We are going to first try using inline assembly for parsing our DMX
* If that doesn't work, we'll attempt to use inline assembly for our I2C control (some simple modifications)
* Also, I (@tylrtrmbl) think that we could study the assembly DMX parsing and implement that in C too
=======
* We are going to first try using inline ASM code to parse the DMX input(Branch: Add-inline-ASM-to-receive-DMX) with the I2C output code written in C
* If that doesn't work, we will attempt to use assembly for everything, both receiving DMX and sending I2C.
* Also, I (@tylrtrmbl) think that we could study the assembly DMX parsing and implement that in C too.
>>>>>>> parent of 7d753be... synced README from master branch
```

So, if you want to keep your edits (which I liked except for naming the branch):
1. Revert your commit that threw away your edits: you want those back!
2. Instead, sync all branches, and then merge them.
3. Resolve the conflict file by manual editing, and then commit.

And then **BOOM**, done.

**Comment by taylortrimble** [comment]
@aterlumen nevermind, I see what's going on now.

**Comment by taylortrimble** [comment]
All right, mildly painful news:

Inline ASM in C18 is very different from mpasm ASM. Specifically:
- No default instructions for operands; we cannot "assume `W` unless specified" or anything like that
- No assembly directives allowed (not an issue for us)

And weird things like:
- Comments must be in C/C++ notation (e.g. `// Comment goes here` not `; Comment goes here`)
- Labels must have a `:` at the end

Our end, ASM code is a weird bastard child that looks something like this:

``` Assembly
_asm
/* User assembly code */
MOVLW 10       // Move decimal 10 to count
MOVWF count, 0

/* Loop until count is 0 */
start:
    DECFSZ count, 1, 0
    GOTO done
    BRA start
done:
_endasm
```

This doesn't mean we can't use inline assembly, it just means that our inline assembly we have now needs to be reformatted. :frowning:

Let's focus on getting something that barely compiles at all (#11) and then get crack-a-lackin. This will help us discover errors in our inline assembly.

Here is a link to the C18 compiler guide: http://ww1.microchip.com/downloads/en/devicedoc/51288f.pdf

**Comment by kevana** [comment]
Alright, I may look into duplicating all of the functionality with C in another branch. After 4061 is done.....

**Comment by taylortrimble** [comment]
Good call. And good luck!

**Comment by kevana** [comment]
Shelving this option in order to use the XC8 compiler for the project.

**Pull request closed without merging**
