### PR TITLE
DMX start channel is currently unread and ignored

### PR DESCRIPTION
**Pull request by taylortrimble**
We aren't reading our DIP switches yet; this can tie into #29 as well.

### CODE REVIEW

**Comment by kevana** [comment]
Isn't this more for the headslave code?

**Comment by taylortrimble** [comment]
Not quite; I2C is really slow to send our entire DMX buffer out, and would destroy our frame rate. Instead, we pick a start address on the master chip and send only the bytes we need to the slaves. Also should cut down on master buffer as well!

**Comment by kevana** [comment]
The I2C send function should only be sending the bytes it needs to the slaves, did you mean for something else?

```
for (i = 0; i < BYTES_PER_SLAVE; ++i) {
sendByte(buffer[BYTES_PER_SLAVE * receiver + i]);
```

**Comment by taylortrimble** [comment]
Ah, yes. I just meant that right now we aren't filling `buffer` at all, and in the future we should be filling it with DMX data starting at whatever start address our DIP switches specify.

**Comment by kevana** [comment]
I think the simplest way to do that would be to read the DIP switch in the
DMXSetup function, but I wasn't aware we were using them.

**Comment by taylortrimble** [comment]
Ah, yes. There's a relatively new note about it [here](https://github.com/teslaworksumn/HeadMaster/wiki/Hardware-Documentation).

**Comment by taylortrimble** [comment]
I wonder how many times I will say "Ah, yes." today. Hopefully not very many more. :stuck_out_tongue:

**Comment by taylortrimble** [comment]
I made the assumption that the DMX value read from PORTA is padded by 4 `0`s. I presumed interaction with multiple animatronic head circuits on one bus isn't that big of an issue, but that we'd theoretically want the heads spaced out anywhere in the DMX frame because other DMX channels were already there and we'd want to be good citizens. I'm curious what @mistressoftheelectron has to say about this though.

**Comment by kevana** [comment]
Sounds good to me. If we wanted to be really good citizens we could run an 8 bit DIP switch through a multiplexer to save pins on the controller, but that would change PCB design.

Since you already added the function here, can you add a variable to store the start channel? I don't want to step on your naming conventions in the other branch.

**Comment by taylortrimble** [comment]
Don't worry about that too much, if I don't like it I'll say something. As for the global variable, we will have to decide how we refactor in #33. What do you say about merging this in, and using it in one of the other pull requests we have open? And @mistressoftheelectron do you have an opinion?

**Comment by kevana** [comment]
Agreed.

**Comment by kevana** [comment]
Merging this into master, will implement start channel logic in #33.

**Pull request merged**
