### PR TITLE
Accept partial DMX frames

### LINKED ISSUE #28: Partial DMX frames not supported
It appears our implementation of `DMXReceive` does not return for frames less than 512 (`DMX_BUFFER_SIZE`) bytes. Instead, if a partial frame is received, it thinks this is an error and attempts a resynchronization.

The DMX standard allows for partial frames, and many consoles implement them.

### PR DESCRIPTION
**Pull request by taylortrimble**
If we get a partial (non-512-byte) DMX frame, we recover.
Thanks @aterlumen for the commits!

I think that this will be a long chain; we'll have to decide what is an error for an incomplete frame and when we are just correctly receiving a partial frame.

Fixes #28, resets RCIF when it is not cleared automatically.

### CODE REVIEW

**Comment by taylortrimble** [comment]
I think this is a good start. Here's what I said in the corresponding issue, additionally:

I think that to do this we should refactor `DMXReceive` or `DMXSetup` a little bit. We should specify the following that our `DMXReceive` function should consider:
- The DMX Start Address
- The number of DMX channels to read
  Then, our `DMXReceive` function can just run until it has gotten to the start address and read in the number of bytes it expects. This solves both this issue and #29.

**Comment by taylortrimble** [comment]
Okay, so I'm going to propose a larger refactor here! I think this will work.

I'm going to propose something like object-oriented C, which is something you're probably familiar with even if you don't think you are.

Here's the "object":

``` C
typedef struct _DMXDevice {
    char *buffer;
    int bufferSize;
    int startAddress;
} DMXDevice
```

And here are the "methods":

``` C
void DMXSetup(DMXDevice *device, int startAddress, int bufferSize);
void DMXSetFrame(DMXDevice *device, int startAddress, int bufferSize);
void DMXReceive(DMXDevice *device);
```

Then, `DMXReceive` can use the object state to receive partial DMX frames, like so (pseudocode):

```
if (bytesReceived < startAddress) {
    // Just increment the byte count
} else if (bytesReceived < (startAddress + frameLength)) {
    // Load byte into DMX buffer
} else {
    // state = DMXDone
}
```

Added benefit: if we are reading bytes at the front of the frame, we will exit before the frame is done and we can move on to other work (like I2C) and come back in time for the next frame. Increased update rate!

**Comment by kevana** [comment]
For ultimate efficiency we could switch to interrupt driven input, then
we'd never have to worry about waiting for the part of the frame we're
interested in. But that would take more work than I think we need. Looks
good to me.

**Comment by taylortrimble** [comment]
Wow, that would be efficient. I think you can describe what you're thinking better, so if you wanted to you could open an issue and we'll maybe get to it in the future.

**Comment by kevana** [comment]
Problem: It looks like the only way to clear the RCIF flag is to read RCREG. I think this gives us two options for partial frames:
1. Use inline assembly to read RCREG into WREG and increment DMXBytesReceived if the value is not between the start and end values we care about. 
2. Use C to either fill the full 512 byte buffer or add a dummy variable to read to if the DMX channel is not between the start and end values specified. 

Option 1 is the most efficient, but I don't think it would be necessary to deal with the assembly because the DMX data is received so slowly anyways. We have over 1000 microcontroller cycles between each DMX byte, so I think this problem is irrelevant.

**Comment by taylortrimble** [comment]
> Problem: It looks like the only way to clear the RCIF flag is to read RCREG. I think this gives us two options for partial frames:
> 1. Use inline assembly to read RCREG into WREG and increment DMXBytesReceived if the value is not between the start and end values we care about. 
> 2. Use C to either fill the full 512 byte buffer or add a dummy variable to read to if the DMX channel is not between the start and end values specified.

I think we can just use the first option in C.

``` C
if (DMXBytesReceived >= DMXStartAddress) {
    DMXBuffer[DMXBytesReceived] = RCREG;
    DMXBytesReceived++;
    if (DMXBytesReceived >= DMXEndAddress) {
        DMXState = DMXDone;
    }
} else {
    DMXInputBuffer = RCREG;
}
```

That is sort of pseudocode, be careful.

**Comment by taylortrimble** [comment]
I am going to try to integrate some of @aterlumen's progress into #38.

**Comment by taylortrimble** [comment]
Okay, some work I did over on #38 may cover this issue. Let me know what ya'll think.

**Comment by taylortrimble** [comment]
I'm closing this unless we determine #38 isn't what we want. Thanks @aterlumen!

**Pull request closed without merging**
