### PR TITLE
Fix issues that keep `master` from compiling

### PR DESCRIPTION
**Pull request by taylortrimble**
All issues that caused build failure in MPLAB X (v 1.10) were hacked away. This is not the same as #3 or our build milestone, because the fixes aren't good enough.

This is just a bare minimum to get no compiler warnings. Configuration is bogus.

### CODE REVIEW

**Comment by taylortrimble** [comment]
@CrasherCourse @aterlumen what do you think?

**Comment by CrasherCourse** [comment]
It compiled for me as well so merge away!

**Comment by kevana** [comment]
Looks good to me.

**Comment by taylortrimble** [comment]
Sweet! Thanks guys.

**Pull request merged**
