### PR TITLE
We won't pull this, but this is the code we have for testing right now.

### PR DESCRIPTION
**Pull request by taylortrimble**
We are having some difficulty with FERR detection. We think that it is only getting a framing error some of the times when it should be. I'll look into this if I have time, but if @aterlumen wants to help out too, that'd be great.

My approach is going to be "rewriting" the recipe for DMX reception based on my knowledge of the protocol, the USART, and the Technote we have on the Wiki for DMX.

### CODE REVIEW

**Comment by kevana** [comment]
Midterm tomorrow morning, but I'll analyze what we have for deviations from the spec.

**Comment by taylortrimble** [comment]
Thank you thank you thank you!

**Comment by CrasherCourse** [comment]
Receive does work.  Test code bug fixed.
Need to remove debugging code.

**Comment by taylortrimble** [comment]
Well, it turns out we are pulling this. Fixed some style and are now throwing away bytes at the front of the packet before the break like we should. Chi-ka-cha! :rocket:

**Pull request merged**
