### PR TITLE
Pull out Magic numbers

### PR DESCRIPTION
**Pull request by taylortrimble**
Replacing integer constants with `#define` directives, and the rest with `const` declarations.
Thanks @aterlumen for the commits!

### CODE REVIEW

**Comment by taylortrimble** [comment]
I know there's a few more constants to hit here; @CrasherCourse can you sniff them out and zap them?

**Comment by kevana** [comment]
I looked through all of the code, I think that's the last one.

**Comment by taylortrimble** [comment]
I found a couple more:
- Inside `mapDmxToServo` (`30` and `1`)
- Global variable arrays inside `I2C.c` (may push `NUMBER_OF_RECEIVERS` to `I2C.h`)

**Comment by kevana** [comment]
I grabbed everything except the mapDmxToServo ones, not sure what you'd want to call them.

**Comment by taylortrimble** [comment]
Something like `SERVO_BIT_OFFSET` and `SERVO_MIN_VALUE` should be sufficient, but you can pick what you like and Kyle or I will say something if we don't like it.

**Comment by taylortrimble** [comment]
Okay, do you see anything else?

**Comment by kevana** [comment]
Nope, that was the only build error I got

**Comment by taylortrimble** [comment]
There's something up with me backing out commits, and I don't want to submit this with 2 huge commits that undo each other, so I'm just going to manually merge.

**Comment by taylortrimble** [comment]
Looks like my plan didn't work, but whatever I guess. Happy coding!

**Pull request merged**
